"use client";
import { useEffect, useState } from "react";
import { Search, RefreshCw } from "lucide-react";
import { ProtectedShell } from "@/components/layout/ProtectedShell";
import { Button, EmptyState, Input, Panel, PageTitle } from "@/components/ui";
import { listAuditLogs } from "@/services/api/auditApi";
import type { AuditLog } from "@/types/api";
export default function AuditLogs() {
  const [items, setItems] = useState<AuditLog[]>([]),
    [q, setQ] = useState("");
  const [publicIPv4, setPublicIPv4] = useState<string | null>(null);
  async function load() {
    try {
      setItems(await listAuditLogs(q ? new URLSearchParams({ search: q }).toString() : ""));
    } catch {}
  }
  useEffect(() => {
    load();
    fetch("https://api.ipify.org?format=json", { cache: "no-store" })
      .then((response) => (response.ok ? response.json() : null))
      .then((data) => {
        if (data?.ip) setPublicIPv4(String(data.ip));
      })
      .catch(() => setPublicIPv4(null));
  }, []);
  return (
    <ProtectedShell>
      <PageTitle
        title="Audit Logs"
        description="Search immutable security events generated by the backend."
        action={
          <Button variant="ghost" onClick={load}>
            <RefreshCw className="h-4 w-4" />
            Refresh
          </Button>
        }
      />
      <Panel className="overflow-hidden">
        <div className="border-b border-white/10 p-4">
          <div className="relative max-w-md">
            <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-600" />
            <Input
              value={q}
              onChange={(e) => setQ(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && load()}
              placeholder="Search action, resource, IP or description"
              className="pl-10"
            />
          </div>
        </div>
        <div className="overflow-x-auto">
          {items.length ? (
            <table className="w-full text-left text-sm">
              <thead className="border-b border-white/10 text-xs uppercase tracking-wide text-slate-600">
                <tr>
                  <th className="px-5 py-4">Action</th>
                  <th className="px-5 py-4">Description</th>
                  <th className="px-5 py-4">IP</th>
                  <th className="px-5 py-4">Status</th>
                  <th className="px-5 py-4">Time</th>
                </tr>
              </thead>
              <tbody>
                {items.map((x) => (
                  <tr key={x.id} className="border-b border-white/5">
                    <td className="px-5 py-4 text-cyan-200">{x.action}</td>
                    <td className="max-w-xl px-5 py-4 text-slate-400">{x.description}</td>
                    <td className="px-5 py-4 text-slate-500">
                      <div>{x.ip_address || "Unknown"}</div>
                      {publicIPv4 && (
                        <div className="mt-1 text-xs text-cyan-300/80">
                          IPv4: {publicIPv4}
                        </div>
                      )}
                    </td>
                    <td className="px-5 py-4 text-slate-400">{x.status}</td>
                    <td className="px-5 py-4 text-slate-500">
                      {new Date(x.created_at).toLocaleString()}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          ) : (
            <div className="p-8">
              <EmptyState text="No audit logs found." />
            </div>
          )}
        </div>
      </Panel>
    </ProtectedShell>
  );
}
